services:
  api:
    build: .
    command: uvicorn mlops.api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app

  ui_nicegui:
    build: .
    command: python ui_nicegui/app.py
    ports:
      - "8502:8502"
    env_file:
      - .env
    volumes:
      - .:/app
